### ISSUE TITLE
new plugin: infobox

### ISSUE THREAD

**Issue by FWirtz** [serlo-org/ory-editor-plugins#7]
As discussed in the call with @schul-cloud last week, a plugin for an infobox is desired.

We thought about two possible design ideas that we would like to discuss. As we need the `Slate` Plugin for editing capabilities these two ideas came to our mind:
1) Wrap the `Slate` Plugin in our `infobox` plugin (i.e. `<infobox><Slate /></infobox>`)
1) Extend the `Slate`plugin with an extra button to toggle the `infobox` style

How do you feel about these suggestions?

@jprberlin @Knorrke

**Comment by Knorrke** [comment]
Hey @FWirtz, thanks for looking into this! I think wrapping the `Slate` Plugin is ok, but maybe this could also be solved with a Layout Plugin in the ory editor, they already provide a way to wrap other cells and plugins :) see the description in the User Guide for more reference: https://ory.gitbooks.io/editor/content/#how-it-works

Maybe looking at a plugin we wrote a while ago for spoilers will help you: https://github.com/serlo-org/ory-editor-spoiler/tree/master/src
(I want to merge this plugin into this new repository, just didn't get to it yet)

**Comment by FWirtz** [comment]
Thanks so much, very helpful!
We will work on that.

**Comment by Blubl** [comment]
So we gave it our best but can't seem to be getting any further based on the docs:
We copied the [`BlackBorder` Layout Plugin](https://ory.gitbooks.io/editor/content/tutorials.html#writing-a-layout-plugin), built it and even managed to import it after a couple of tries.
Once we drag it into the ory-editor however it **instantly disappears**.

We believe that this might be due to a missing `createInitialChildren` function. We attempted to grab it from the [spoiler plugin](https://github.com/serlo-org/ory-editor-spoiler/tree/master/src) you suggested but this just causes different errors.

@Knorrke Can you maybe suggest how to implement `createInitialChildren` properly or even tell us if the immediate disappearing is due to that? That would be really nice 😏

**Comment by Knorrke** [comment]
Hey @Blubl good catch, the docs aren't complete there. Probably there was a breaking change, that layout plugins are removed if they're empty... I'll update the docs later this week! Sorry for the inconvenience :-)

As for your question: The way we handled the initialChildrens is, that we initialize the layout plugin with a defaultPlugin as child. So instead of 
```javascript
export default {
  //... plugin definition here
}
```
it should be
```javascript
export default ({ defaultPlugin }) => ({
  //... plugin definition here
 createInitialChildren: () => ({
    id: uuid(),
    rows: [{
      id: uuid(),
      cells: [{
        content: { plugin: defaultPlugin, state: defaultPlugin.createInitialState() },
        id: uuid(),
      }]
    }]
  }) 
})
```

This makes sense, so the slate plugin can be initialized with additional settings if needed, without changing the `infobox` plugin.

In order to use the plugin, you have to add it in the example to the layouts and pass it the defaultPlugin like the following:

```javascript
const plugins = {
  content: [
    //... content plugins here
  ],
  layout: [
    infobox({ defaultPlugin: slate() })
  ]
}
```


Hope this helps, if you have any trouble getting this to run please feel free to ask! :-) Also it would be great if you document where you have problems with creating a plugin or understanding and running the docs, so we can improve the guides! Thanks for your work

**Comment by FWirtz** [comment]
Thanks @Knorrke, we are on it.
Another question: If we take a look at the spoiler plugin, why is there a mismatch between the `package.json` and the meta section in `src/index.js` of the plugin regarding the version? One states `0.0.0` and the other states `0.0.1`. Are both versions used or can we omit one?
Also, why do the names differ?
In the `package.json` it's called `ory-editor-plugins-infobox`, in the `title` of the `src/index.js` meta section it's called `ory/editor/core/layout/spoiler`.
Is the naming in the `src/index.js` important and according to some conventions or is this irrelevant?
We find this slightly confusing.

**Comment by Knorrke** [comment]
Don't know why the versions missmatch, i think keeping these versions the same does make sense. However they (as well as the name) have a different purpose in the `package.json` and in `index.js`:

the package.json defines version and name for npm publishing and follows that conventions (the spoiler plugin sn't published atm, so they don't really matter).

The name and version in the index.js however are for the editor itself, so it can serialize and deserialize the plugins. I think there's no convention for this name but it should be possible to include the plugin without name collisions in any website using the ory editor.

So the names and versions in `index.js` and `package.json` are not dependent on each other. This means you need both but it doesn't matter if they are the same or not. 

Also as a side note: its possible to have multiple plugins in one repo, so you don't have a package.json for each of them. But the way we do it here one can add each plugin individually through npm like having a repo for every one of them

**Comment by jprberlin** [comment]
Can I get a Screenshot ...

**Comment by FWirtz** [comment]
You sure can @jprberlin, just have a look at the PR. ☺️
